name: 'npm-semver-publish-action'
description:
  'GitHub action to publish npm packages with semanantic versioning rules'
author: 'iuccio'

# Define your inputs here.
inputs:
  target-branch:
    description:
      'Branch name where npm publish with semanantic versioning should be
      applied to the GitHub Action execution'
    required: true
    default: 'master'

# Define your outputs here.
outputs:
  version:
    description: 'Published release version'

runs:
  using: node20
  main: dist/index.js
